// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANXKCnBg4iq6ibozq4bb5FQflnZlaMVlc',
    appId: '1:370306486123:web:f9db6b8d66152e99c9462e',
    messagingSenderId: '370306486123',
    projectId: 'lost-and-found-97481',
    authDomain: 'lost-and-found-97481.firebaseapp.com',
    storageBucket: 'lost-and-found-97481.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrTVWLlxpN5SjvBb1KlDmiZg7AlKlpqdw',
    appId: '1:370306486123:android:ec3185cc64dd41dcc9462e',
    messagingSenderId: '370306486123',
    projectId: 'lost-and-found-97481',
    storageBucket: 'lost-and-found-97481.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT0dvaazKrYSUsbnts7qgBN96aPbUaVtM',
    appId: '1:370306486123:ios:763c348fdbe909f2c9462e',
    messagingSenderId: '370306486123',
    projectId: 'lost-and-found-97481',
    storageBucket: 'lost-and-found-97481.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFoundFnlyrprj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT0dvaazKrYSUsbnts7qgBN96aPbUaVtM',
    appId: '1:370306486123:ios:763c348fdbe909f2c9462e',
    messagingSenderId: '370306486123',
    projectId: 'lost-and-found-97481',
    storageBucket: 'lost-and-found-97481.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFoundFnlyrprj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANXKCnBg4iq6ibozq4bb5FQflnZlaMVlc',
    appId: '1:370306486123:web:e8f6fb085ac26d4ec9462e',
    messagingSenderId: '370306486123',
    projectId: 'lost-and-found-97481',
    authDomain: 'lost-and-found-97481.firebaseapp.com',
    storageBucket: 'lost-and-found-97481.firebasestorage.app',
  );
}
